# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 818717d17ec11f214f9c9337662a8468ddc2b8c242f51779688e64add09198938d43d72ad5b746331e4556fc6625e0aedda97f24f30f91131e837f1d6bcba135

test:
  secret_key_base: 85f86d24c470de14d7b90bf2dbe456145877c7a40823f45c0c10e0d23b25ffc25ddfef17b9c6a700c3fc32988eb50b922d16b2c5eeca10431c0e1085962e00d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
